name: chatme
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.1







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  gap: ^3.0.1
  google_fonts: ^6.2.1
  change_app_package_name: ^1.3.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  elegant_notification: ^2.2.2
  cloud_firestore: ^4.14.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializer: ^0.2.0
  build_runner: ^2.4.12
  
  
  
  
  
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "3d52a0"
  image_path: "assets/logo/logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/logo/logo.png"
  color: "#3d52a0"

flutter:

  uses-material-design: true
  assets:
    - assets/logo/
  